# © 2025 Little Shilling, Inc.
# Shon Little
# Created: 2025-06-18

server {
  listen 80;
  server_name littledaisy.org;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }
}
